import Header from "@/components/Header"
import Head from "next/head"

export default function Home() {
  return (
    <div>
      <Head>
        <title>ReQues App</title>
        <meta name="description" content="Generated by create nex app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  )
}
